'use client'

import { useMemo, useState } from 'react'
import { ArrowRight, Clock3, Heart, Minus, Plus, Search, ShoppingBag, SlidersHorizontal, Star, X, CheckCircle2, ChevronRight } from 'lucide-react'
import { AppFrame, DemoNotice, Money, SectionHeading, StatusPill } from '@/components/app-shell'
import { getProductsByStoreId, mockProducts, mockStores, type Product, type Store } from '@/lib/mock-data'

export default function ClientePage() {
  const [search, setSearch] = useState('')
  const [selectedStore, setSelectedStore] = useState<Store | null>(null)
  const [cart, setCart] = useState<{ product: Product; quantity: number }[]>([])
  const [showCart, setShowCart] = useState(false)
  const [ordered, setOrdered] = useState(false)
  const [view, setView] = useState<'stores' | 'pedidos'>('stores')

  const filteredStores = useMemo(() => mockStores.filter((store) => store.name.toLowerCase().includes(search.toLowerCase()) || store.address.toLowerCase().includes(search.toLowerCase())), [search])
  const products = selectedStore ? getProductsByStoreId(selectedStore.id) : []
  const cartTotal = cart.reduce((sum, item) => sum + item.product.price * item.quantity, 0)
  const cartCount = cart.reduce((sum, item) => sum + item.quantity, 0)

  function addToCart(product: Product) { setCart((items) => { const found = items.find((item) => item.product.id === product.id); return found ? items.map((item) => item.product.id === product.id ? { ...item, quantity: item.quantity + 1 } : item) : [...items, { product, quantity: 1 }] }) }
  function changeQuantity(id: string, amount: number) { setCart((items) => items.map((item) => item.product.id === id ? { ...item, quantity: item.quantity + amount } : item).filter((item) => item.quantity > 0)) }
  function finalizeOrder() { setShowCart(false); setOrdered(true); setCart([]) }

  return <AppFrame profile="cliente"><div className="mx-auto max-w-6xl"><DemoNotice>Você está navegando como <strong>João da Silva</strong>. Este é um ambiente de demonstração com pedidos simulados.</DemoNotice>{ordered ? <OrderSuccess onBack={() => setOrdered(false)} /> : view === 'pedidos' ? <OrdersView onBack={() => setView('stores')} /> : <><SectionHeading eyebrow="Seu próximo açaí" title="Escolha uma batedeira" description="Açaí tradicional, batido na hora e pertinho de você." action={<button onClick={() => setShowCart(true)} className="relative inline-flex items-center gap-2 rounded-full bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground shadow-sm"><ShoppingBag className="size-4" /> Sacola {cartCount > 0 && <span className="grid size-5 place-items-center rounded-full bg-accent text-[11px] text-accent-foreground">{cartCount}</span>}</button>} /><div className="mb-8 flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar batedeira ou bairro" className="h-12 w-full rounded-2xl border border-border bg-card pl-11 pr-4 text-sm outline-none ring-primary/20 transition placeholder:text-muted-foreground focus:ring-4" /></label><button className="inline-flex h-12 items-center justify-center gap-2 rounded-2xl border border-border bg-card px-4 text-sm font-semibold text-muted-foreground"><SlidersHorizontal className="size-4" /> Filtros</button><button onClick={() => setView('pedidos')} className="inline-flex h-12 items-center justify-center gap-2 rounded-2xl border border-border bg-card px-4 text-sm font-semibold text-muted-foreground"><Clock3 className="size-4" /> Meus pedidos</button></div><div className="mb-5 flex items-center justify-between"><p className="text-sm text-muted-foreground"><strong className="text-foreground">{filteredStores.length} batedeiras</strong> encontradas perto de você</p><select className="rounded-xl border border-border bg-card px-3 py-2 text-xs font-semibold text-muted-foreground"><option>Mais próximas</option><option>Melhor avaliadas</option></select></div><div className="grid gap-5 md:grid-cols-2">{filteredStores.map((store) => <StoreCard key={store.id} store={store} onClick={() => store.isOpen && setSelectedStore(store)} />)}</div></>}{selectedStore && <StoreMenu store={selectedStore} products={products} onClose={() => setSelectedStore(null)} onAdd={addToCart} />}{showCart && <CartPanel cart={cart} total={cartTotal} onClose={() => setShowCart(false)} onChange={changeQuantity} onFinalize={finalizeOrder} />}</div></AppFrame>
}

function StoreCard({ store, onClick }: { store: Store; onClick: () => void }) { return <article onClick={onClick} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') onClick() }} role="button" tabIndex={store.isOpen ? 0 : -1} aria-disabled={!store.isOpen} className={`group overflow-hidden rounded-3xl border border-border bg-card text-left shadow-sm transition ${store.isOpen ? 'cursor-pointer hover:-translate-y-1 hover:shadow-xl' : 'opacity-70'}`}><div className="relative aspect-[1.8] overflow-hidden"><img src={store.image} alt={store.name} className="size-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute left-4 top-4"><StatusPill status={store.status} /></div><button aria-label="Favoritar" onClick={(e) => e.stopPropagation()} className="absolute right-4 top-4 grid size-9 place-items-center rounded-full bg-background/85 text-muted-foreground backdrop-blur"><Heart className="size-4" /></button></div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-black">{store.name}</h3><p className="mt-1 text-xs text-muted-foreground">{store.address}</p></div><span className="flex items-center gap-1 text-sm font-bold"><Star className="size-4 fill-accent text-accent" />{store.rating}</span></div><div className="mt-5 flex items-center justify-between border-t border-border pt-4 text-xs text-muted-foreground"><span>{store.distance.toFixed(1).replace('.', ',')} km de distância</span><span>{store.isOpen ? `Fila: ${store.queueSize} pedidos` : 'Volta amanhã'}</span></div></div></article> }

function StoreMenu({ store, products, onClose, onAdd }: { store: Store; products: Product[]; onClose: () => void; onAdd: (product: Product) => void }) { return <div className="fixed inset-0 z-50 flex items-end justify-center bg-foreground/40 p-0 backdrop-blur-sm sm:items-center sm:p-6"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-t-[2rem] bg-background p-5 shadow-2xl sm:rounded-[2rem] sm:p-8"><div className="mb-6 flex items-start justify-between"><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.18em] text-secondary">Cardápio da batedeira</p><h2 className="text-2xl font-black">{store.name}</h2><p className="mt-1 text-sm text-muted-foreground">{store.address} · {store.distance.toFixed(1).replace('.', ',')} km</p></div><button onClick={onClose} aria-label="Fechar cardápio" className="grid size-10 place-items-center rounded-full bg-muted"><X className="size-5" /></button></div><div className="grid gap-3">{products.map((product) => <div key={product.id} className="flex gap-4 rounded-2xl border border-border bg-card p-3"><img src={product.image} alt={product.name} className="size-24 rounded-xl object-cover" /><div className="min-w-0 flex-1"><h3 className="font-black">{product.name}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{product.description}</p><div className="mt-3 flex items-center justify-between"><span className="font-black text-primary"><Money value={product.price} /></span><button onClick={() => onAdd(product)} className="inline-flex items-center gap-1.5 rounded-full bg-primary px-3 py-2 text-xs font-bold text-primary-foreground"><Plus className="size-3.5" /> Adicionar</button></div></div></div>)}</div></div></div> }

function CartPanel({ cart, total, onClose, onChange, onFinalize }: { cart: { product: Product; quantity: number }[]; total: number; onClose: () => void; onChange: (id: string, amount: number) => void; onFinalize: () => void }) { return <div className="fixed inset-0 z-50 flex justify-end bg-foreground/40 backdrop-blur-sm"><div className="flex h-full w-full max-w-md flex-col bg-background p-6 shadow-2xl sm:p-8"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-secondary">Sua sacola</p><h2 className="mt-2 text-2xl font-black">Pedido em aberto</h2></div><button onClick={onClose} aria-label="Fechar sacola" className="grid size-10 place-items-center rounded-full bg-muted"><X className="size-5" /></button></div>{cart.length === 0 ? <div className="flex flex-1 flex-col items-center justify-center text-center"><ShoppingBag className="mb-4 size-10 text-muted-foreground/40" /><p className="font-bold">Sua sacola está vazia</p><p className="mt-2 text-sm text-muted-foreground">Adicione um açaí para começar.</p></div> : <><div className="flex flex-1 flex-col gap-3 overflow-y-auto py-8">{cart.map(({ product, quantity }) => <div key={product.id} className="flex items-center gap-3 rounded-2xl border border-border bg-card p-3"><img src={product.image} alt="" className="size-14 rounded-xl object-cover" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{product.name}</p><p className="text-xs text-muted-foreground"><Money value={product.price} /></p></div><div className="flex items-center gap-2 rounded-xl bg-muted p-1"><button onClick={() => onChange(product.id, -1)} aria-label="Diminuir quantidade" className="grid size-6 place-items-center rounded-lg"><Minus className="size-3" /></button><span className="w-4 text-center text-xs font-bold">{quantity}</span><button onClick={() => onChange(product.id, 1)} aria-label="Aumentar quantidade" className="grid size-6 place-items-center rounded-lg"><Plus className="size-3" /></button></div></div>)}</div><div className="border-t border-border pt-5"><div className="mb-4 flex items-center justify-between text-sm"><span className="text-muted-foreground">Subtotal</span><strong className="text-xl"><Money value={total} /></strong></div><button onClick={onFinalize} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-primary py-3.5 text-sm font-bold text-primary-foreground">Confirmar pedido <ArrowRight className="size-4" /></button><p className="mt-3 text-center text-xs text-muted-foreground">Pagamento na retirada · demonstração</p></div></>}</div></div> }

function OrderSuccess({ onBack }: { onBack: () => void }) { return <div className="mx-auto max-w-xl py-16 text-center"><div className="mx-auto mb-6 grid size-20 place-items-center rounded-full bg-secondary/15 text-secondary"><CheckCircle2 className="size-10" /></div><p className="mb-2 text-xs font-bold uppercase tracking-[0.18em] text-secondary">Pedido enviado</p><h1 className="text-4xl font-black tracking-tight">Seu açaí já está sendo preparado.</h1><p className="mx-auto mt-4 max-w-md text-sm leading-6 text-muted-foreground">A batedeira recebeu seu pedido. Você pode acompanhar cada etapa por aqui.</p><div className="mt-8 rounded-3xl border border-border bg-card p-6 text-left shadow-sm"><div className="flex items-center justify-between"><span className="text-sm font-bold">Pedido #AC-1042</span><StatusPill status="confirmed" /></div><div className="mt-6 flex items-center justify-between"><div className="flex flex-col items-center gap-2 text-center"><span className="grid size-9 place-items-center rounded-full bg-primary text-xs font-bold text-primary-foreground">1</span><span className="text-[11px] font-semibold">Recebido</span></div><div className="h-px flex-1 bg-primary" /><div className="flex flex-col items-center gap-2 text-center"><span className="grid size-9 place-items-center rounded-full bg-primary text-xs font-bold text-primary-foreground">2</span><span className="text-[11px] font-semibold">Confirmado</span></div><div className="h-px flex-1 bg-border" /><div className="flex flex-col items-center gap-2 text-center text-muted-foreground"><span className="grid size-9 place-items-center rounded-full bg-muted text-xs font-bold">3</span><span className="text-[11px] font-semibold">Pronto</span></div></div><p className="mt-6 text-center text-sm text-muted-foreground">Previsão de retirada: <strong className="text-foreground">20–25 min</strong></p></div><button onClick={onBack} className="mt-6 inline-flex items-center gap-2 rounded-full border border-border px-5 py-3 text-sm font-bold"><ChevronRight className="size-4 rotate-180" /> Voltar para batedeiras</button></div> }

function OrdersView({ onBack }: { onBack: () => void }) { return <><SectionHeading eyebrow="Histórico" title="Meus pedidos" description="Acompanhe pedidos atuais e reveja suas escolhas favoritas." action={<button onClick={onBack} className="rounded-full border border-border px-4 py-2.5 text-sm font-bold">Explorar batedeiras</button>} /><div className="grid gap-4">{[{ id: '#AC-1038', store: 'Açaí do Seu João', status: 'delivered' as const, total: 42, date: 'Hoje, 12:34' }, { id: '#AC-1021', store: 'Açaí Amazônia', status: 'delivered' as const, total: 28, date: 'Ontem, 18:12' }, { id: '#AC-0984', store: 'Puro Açaí', status: 'delivered' as const, total: 54, date: '12 de maio, 16:40' }].map((order) => <div key={order.id} className="flex flex-col gap-4 rounded-2xl border border-border bg-card p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-3"><span className="font-black">{order.store}</span><StatusPill status={order.status} /></div><p className="mt-2 text-xs text-muted-foreground">Pedido {order.id} · {order.date}</p></div><div className="flex items-center justify-between gap-5 sm:justify-end"><strong><Money value={order.total} /></strong><button className="inline-flex items-center gap-1 text-xs font-bold text-primary">Ver detalhes <ChevronRight className="size-3.5" /></button></div></div>)}</div></> }
