'use client'

import { useState } from 'react'
import { Activity, Check, Clock3, Store as StoreIcon } from 'lucide-react'
import { AppFrame, SectionHeading, StatCard, useToast } from '@/components/app-shell'
import { usePrototype } from '@/components/prototype-provider'
import { PhotoField } from '@/components/photo-field'
import { formatDuration, pilotMetrics } from '@/lib/order-presentation'
import { Modal } from '@/components/modal'
import { OrderPanel } from '@/components/order-panel'
import { RoleLogin, RoleSignedInBar, useRoleSignIn } from '@/components/role-login'
import { useView } from '@/lib/use-view'
import { adminActorName, adminStatusLabel, cents, guestCustomerName, isStoreOpenNow, mockNeighborhoods, type AdminStatus, type Store } from '@/lib/mock-data'

function AdminLogin({onSignIn}:{onSignIn:(email:string)=>void}) {
  const [email,setEmail]=useState('')
  const [password,setPassword]=useState('')
  return <RoleLogin title="Entrar na central administrativa" description="Acesse com o e-mail do administrador do piloto. Esta etapa ainda não realiza autenticação no servidor; use uma senha de teste, nunca uma senha real." onSubmit={event=>{event.preventDefault();onSignIn(email.trim()||adminActorName)}}>
    <label>E-mail<input className="demo-field" required type="email" maxLength={254} autoComplete="off" value={email} onChange={event=>setEmail(event.target.value)} /></label>
    <label>Senha<input className="demo-field" required type="password" autoComplete="off" value={password} onChange={event=>setPassword(event.target.value)} /><span className="text-xs text-muted-foreground">Use uma senha de teste — não a sua senha real.</span></label>
  </RoleLogin>
}

export default function AdminPage() {
  const demo=usePrototype()
  const notify=useToast()
  const [view,setView]=useView()
  const [editing,setEditing]=useState<Store|null>(null)
  const [reason,setReason]=useState('')
  const [eligible,setEligible]=useState(false)
  const [error,setError]=useState('')
  const [supportEmail,setSupportEmail]=useState(demo.supportEmail)
  const [accountReason,setAccountReason]=useState('')
  const [signedIn,setSignedIn]=useRoleSignIn('acaiconecta-admin-signed-in')
  const [adminEmail,setAdminEmail]=useState(adminActorName)
  const orders=demo.orders
  const metrics=pilotMetrics(orders)
  const responded=orders.filter(o=>o.timeline.some(e=>e.to==='ACEITO'||e.to==='RECUSADO'))
  const accepted=orders.filter(o=>o.timeline.some(e=>e.to==='ACEITO'))
  const percentage=(numerator:number,denominator:number)=>denominator?`${Math.round(numerator/denominator*100)}%`:'Sem dados'
  const actor={role:'admin' as const,name:adminActorName}
  function edit(store:Store) {setEditing({...store});setReason('');setEligible(false);setError('')}
  function save() {
    try{if(!editing)return;if(!reason.trim())throw new Error('Informe o motivo administrativo.');if(editing.adminStatus==='ATIVA'&&!eligible)throw new Error('Confirme a verificação externa de elegibilidade.');demo.updateStore(editing,reason);setEditing(null);notify('Cadastro e auditoria atualizados.')}
    catch(error){setError(error instanceof Error?error.message:'Revise os dados.')}
  }
  if(!signedIn) return <AppFrame profile="admin"><AdminLogin onSignIn={email=>{setAdminEmail(email);setSignedIn(true)}} /></AppFrame>
  return <AppFrame profile="admin"><div className="mx-auto max-w-6xl">
    <RoleSignedInBar onSignOut={()=>setSignedIn(false)}>Conectado como <b>{adminEmail}</b></RoleSignedInBar>
    <SectionHeading eyebrow="Administração" title="Supervisão do piloto" description="Resultados calculados a partir dos pedidos registrados nesta sessão."/>
    <nav className="mb-6 flex flex-wrap gap-2" aria-label="Seções administrativas">{[['overview','Visão geral'],['lojas','Batedeiras'],['pedidos','Pedidos e auditoria'],['usuarios','Usuários'],['suporte','Suporte e cobertura']].map(([key,label])=><button key={key} className="demo-button" aria-pressed={view===key} onClick={()=>setView(key)}>{label}</button>)}</nav>
    {view==='overview'&&<><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard label="Batedeiras ativas" value={String(demo.stores.filter(s=>s.adminStatus==='ATIVA').length)} detail="Nesta sessão" icon={StoreIcon}/><StatCard label="Taxa de aceite" value={percentage(accepted.length,responded.length)} detail="Aceitos / respondidos" icon={Check}/><StatCard label="Conclusão" value={percentage(orders.filter(o=>o.status==='ENTREGUE').length,accepted.length)} detail="Entregues / aceitos" icon={Activity}/><StatCard label="Expiração" value={percentage(orders.filter(o=>o.status==='EXPIRADO').length,orders.length)} detail="Expirados / enviados" icon={Clock3}/></div><dl className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border p-4"><dt className="text-sm">Resposta em até 5 minutos</dt><dd className="text-xl font-bold">{percentage(metrics.responseWithinFiveMinutes,metrics.sent)}</dd><p className="text-xs text-muted-foreground">Respondidos em até 5 min / enviados</p></div><div className="rounded-xl border p-4"><dt className="text-sm">Cancelamento após aceite</dt><dd className="text-xl font-bold">{percentage(metrics.cancelledAfterAcceptance,metrics.accepted)}</dd><p className="text-xs text-muted-foreground">Cancelados após aceite / aceitos</p></div></dl><section className="mt-4 rounded-xl border p-4"><h2 className="font-bold">Entregas por batedeira nos últimos 7 dias</h2>{demo.stores.map(store=><p className="mt-2 text-sm" key={store.id}>{store.name}: {orders.filter(order=>order.storeId===store.id&&order.status==='ENTREGUE'&&order.timeline.some(event=>event.to==='ENTREGUE'&&Date.parse(event.at)>=demo.now-7*86400000)).length}</p>)}</section>
    <section className="mt-4 rounded-xl border p-4"><h2 className="font-bold">Métricas de apoio</h2><dl className="mt-3 grid gap-3 sm:grid-cols-2"><div><dt className="text-sm">Carrinhos iniciados → pedidos enviados</dt><dd className="font-bold">{demo.cartsStarted} → {orders.length} ({percentage(orders.length,demo.cartsStarted)})</dd></div><div><dt className="text-sm">Tempo médio até aceite ou recusa</dt><dd className="font-bold">{formatDuration(metrics.avgResponseMs)}</dd></div><div><dt className="text-sm">Tempo médio entre aceite e saída</dt><dd className="font-bold">{formatDuration(metrics.avgAcceptToDispatchMs)}</dd></div><div><dt className="text-sm">Tempo médio total até entrega</dt><dd className="font-bold">{formatDuration(metrics.avgDeliveryMs)}</dd></div><div><dt className="text-sm">Clientes ativos</dt><dd className="font-bold">{metrics.activeCustomers}</dd></div><div><dt className="text-sm">Recompra em até 30 dias</dt><dd className="font-bold">{metrics.recurrenceRate===null?'Sem dados suficientes':`${Math.round(metrics.recurrenceRate*100)}%`}</dd></div><div><dt className="text-sm">Batedeiras com entrega nos últimos 7 dias</dt><dd className="font-bold">{metrics.activeStoresLastWeek}</dd></div></dl>
      <div className="mt-4 grid gap-3 sm:grid-cols-3">{([['Motivos de recusa',metrics.refusalReasons],['Motivos de cancelamento',metrics.cancellationReasons],['Motivos de falha na entrega',metrics.failureReasons]] as const).map(([label,list])=><div key={label}><h3 className="text-sm font-bold">{label}</h3>{list.length===0?<p className="text-xs text-muted-foreground">Nenhum registro.</p>:<ul className="mt-1 space-y-1 text-xs">{list.map(entry=><li key={entry.reason}>{entry.reason} · {entry.count}</li>)}</ul>}</div>)}</div>
      <p className="mt-3 text-xs text-muted-foreground">Motivo registrado em 100% das recusas e cancelamentos exigidos pela máquina de estados desta simulação.</p>
    </section>
    <p className="mt-5 rounded-xl bg-muted p-4 text-sm">Estas métricas não substituem a evidência do piloto real. Pagamentos são realizados diretamente na entrega; não há receita ou caixa confirmado pela plataforma.</p></>}
    {view==='lojas'&&<><button className="demo-primary mb-5" onClick={()=>edit({id:crypto.randomUUID(),name:'',owner:'',operator:'',operatorEmail:'',address:'',neighborhood:'Centro',image:'/placeholder.svg',adminStatus:'EM_ANALISE',isOpen:false,deliveryAvailable:false,hours:'09h às 18h',estimatedRange:'25–35 min',deliveryFeeCents:0,createdAt:new Date().toISOString()})}>Cadastrar batedeira e operador</button><div className="grid gap-4 sm:grid-cols-2">{demo.stores.map(store=><article key={store.id} className="rounded-2xl border bg-card p-5"><h2 className="text-xl font-bold">{store.name}</h2><p className="mt-2">{adminStatusLabel(store.adminStatus)}</p><p className="text-sm">Operador responsável: {store.operator}</p><p className="text-sm">Login do operador: {store.operatorEmail}</p><p className="text-sm">{store.address} · {store.neighborhood}</p><p className="text-sm">{isStoreOpenNow(store)?'Aberta agora':'Fechada agora'} · {store.deliveryAvailable?'Entrega disponível':'Entrega indisponível'} · R$ {cents(store.deliveryFeeCents)}</p><button className="demo-button mt-4" onClick={()=>edit(store)}>Revisar cadastro e situação</button></article>)}</div></>}
    {view==='pedidos'&&<><div className="grid gap-4">{orders.length===0&&<p>Nenhum pedido registrado ainda.</p>}{orders.map(order=><OrderPanel key={order.id} order={order} actor={actor}/>)}</div><section className="mt-8"><h2 className="mb-4 text-2xl font-bold">Trilha de auditoria</h2>{demo.audit.length===0?<p>Nenhuma intervenção administrativa registrada.</p>:<ol className="space-y-3">{demo.audit.slice().reverse().map(event=><li key={event.id} className="rounded-xl border bg-card p-4 text-sm"><b>{event.action}</b> · {new Date(event.at).toLocaleString('pt-BR',{timeZone:'America/Belem'})}<p>{event.author} · {event.entityId}</p><p>{event.reason}</p></li>)}</ol>}</section><p className="mt-4 text-sm">Incidentes do piloto continuam no diário operacional externo. Este registro representa intervenções administrativas nesta sessão.</p></>}
    {view==='usuarios'&&<><h2 className="mb-4 text-xl font-bold">Acesso de clientes</h2><div className="rounded-xl border bg-card p-4"><p>{demo.customer.name||guestCustomerName} · {demo.customerBlocked?'Bloqueado':'Ativo'}</p><p className="my-3 text-sm text-muted-foreground">O bloqueio impede novos envios e novas entradas. O histórico é preservado. Recuperação de acesso é assistida pelo suporte; não existe envio de senha.</p><form className="space-y-3" onSubmit={event=>{event.preventDefault();try{demo.setCustomerBlocked(!demo.customerBlocked,accountReason);setAccountReason('');notify('Situação da conta atualizada e auditada.')}catch(error){notify(error instanceof Error?error.message:'Revise os dados.','error')}}}><label>Motivo administrativo<textarea required maxLength={255} className="demo-field" value={accountReason} onChange={event=>setAccountReason(event.target.value)}/></label><button className="demo-button">{demo.customerBlocked?'Reativar conta':'Bloquear conta'}</button></form></div>
      <h2 className="mb-4 mt-6 text-xl font-bold">Solicitações de recuperação de acesso</h2>
      {demo.accessRequests.length===0?<p className="text-sm">Nenhuma solicitação registrada ainda.</p>:<ul className="space-y-3">{demo.accessRequests.map(request=><li key={request.id} className="rounded-xl border bg-card p-4 text-sm"><p className="font-bold">{request.contact}</p><p>{request.reason}</p><p className="text-xs text-muted-foreground">{new Date(request.createdAt).toLocaleString('pt-BR',{timeZone:'America/Belem'})} · {request.resolved?`Acesso concedido em ${new Date(request.resolvedAt!).toLocaleString('pt-BR',{timeZone:'America/Belem'})}`:'Pendente'}</p>{!request.resolved&&<button className="demo-button mt-2" onClick={()=>{try{demo.resolveAccessRequest(request.id);notify('Acesso concedido e auditado.')}catch(error){notify(error instanceof Error?error.message:'Revise a solicitação.','error')}}}>Conceder acesso</button>}</li>)}</ul>}
      <ul className="mt-6 space-y-3">{demo.stores.map(store=><li key={store.id} className="rounded-xl border bg-card p-4">{store.operator} · Operador único de {store.name}</li>)}</ul></>}
    {view==='suporte'&&<div className="max-w-xl space-y-6">
      <form className="space-y-4 rounded-xl border bg-card p-5" onSubmit={event=>{event.preventDefault();try{demo.configureSupport(supportEmail);notify('Contato de suporte salvo nesta sessão.')}catch(error){notify(error instanceof Error?error.message:'Revise o contato.','error')}}}><h2 className="text-xl font-bold">Suporte</h2><label>E-mail do suporte (opcional nesta etapa)<input type="email" maxLength={254} className="demo-field" value={supportEmail} onChange={event=>setSupportEmail(event.target.value)}/></label><p className="text-sm text-muted-foreground">Sem contato configurado, a ajuda orienta o participante a chamar o responsável pelo teste. Configure o canal oficial antes do piloto. Não há envio automático de mensagens.</p><button className="demo-primary">Salvar contato</button></form>
      <section className="rounded-xl border bg-card p-5"><h2 className="text-xl font-bold">Cobertura de bairros</h2><p className="mt-2 text-sm">O piloto atende somente o bairro Centro, em Cametá/PA. Taxa e faixa estimada são configuradas por batedeira.</p><ul className="mt-3 space-y-2">{mockNeighborhoods.map(neighborhood=><li key={neighborhood.name} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={neighborhood.active} disabled aria-label={`${neighborhood.name}: ${neighborhood.active?'ativo':'fora do piloto'}`}/><span>{neighborhood.name} · {neighborhood.active?'Ativo no piloto':'Fora do piloto'}</span></li>)}</ul><p className="mt-3 text-xs text-muted-foreground">Ativar um novo bairro exige decisão registrada em decisions.md e nova validação operacional; não é uma ação disponível nesta etapa.</p></section>
    </div>}
    {editing&&<Modal title="Cadastro assistido" onClose={()=>setEditing(null)}><form className="space-y-4" onSubmit={e=>{e.preventDefault();save()}}><label>Nome público<input required maxLength={150} className="demo-field" value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>Operador responsável<input required maxLength={150} className="demo-field" value={editing.operator} onChange={e=>setEditing({...editing,operator:e.target.value,owner:e.target.value})}/></label><label>E-mail de login do operador<input required type="email" maxLength={254} autoComplete="off" className="demo-field" value={editing.operatorEmail} onChange={e=>setEditing({...editing,operatorEmail:e.target.value})}/><span className="text-xs text-muted-foreground">Usado pelo operador para simular o acesso em /operador. Deve ser único entre as batedeiras.</span></label><label>Endereço no Centro<input required maxLength={255} className="demo-field" value={editing.address} onChange={e=>setEditing({...editing,address:e.target.value})}/></label><label>Situação<select className="demo-field" value={editing.adminStatus} onChange={e=>setEditing({...editing,adminStatus:e.target.value as AdminStatus})}>{(['EM_ANALISE','ATIVA','SUSPENSA','DESATIVADA'] as AdminStatus[]).map(status=><option key={status} value={status}>{adminStatusLabel(status)}</option>)}</select></label><label className="flex gap-2"><input type="checkbox" checked={eligible} onChange={e=>setEligible(e.target.checked)}/>Elegibilidade conferida fora do sistema (obrigatório para ativar)</label><label>Motivo administrativo<textarea required maxLength={255} className="demo-field" value={reason} onChange={e=>setReason(e.target.value)}/></label><PhotoField value={editing.image} onChange={image=>setEditing({...editing,image})}/>{error&&<p role="alert">{error}</p>}<button className="demo-primary">Salvar e registrar auditoria</button></form></Modal>}
  </div></AppFrame>
}
